export * from './account.service';
import { AccountService } from './account.service';
export * from './class.service';
import { ClassService } from './class.service';
export * from './classSubject.service';
import { ClassSubjectService } from './classSubject.service';
export * from './classSubjectResult.service';
import { ClassSubjectResultService } from './classSubjectResult.service';
export * from './country.service';
import { CountryService } from './country.service';
export * from './localGovernmentArea.service';
import { LocalGovernmentAreaService } from './localGovernmentArea.service';
export * from './schoolConfiguration.service';
import { SchoolConfigurationService } from './schoolConfiguration.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './state.service';
import { StateService } from './state.service';
export * from './student.service';
import { StudentService } from './student.service';
export * from './subject.service';
import { SubjectService } from './subject.service';
export * from './teacher.service';
import { TeacherService } from './teacher.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AccountService, ClassService, ClassSubjectService, ClassSubjectResultService, CountryService, LocalGovernmentAreaService, SchoolConfigurationService, SessionService, StateService, StudentService, SubjectService, TeacherService, WeatherForecastService];
