/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UserType = 0 | 1 | 2;

export const UserType = {
    NUMBER_0: 0 as UserType,
    NUMBER_1: 1 as UserType,
    NUMBER_2: 2 as UserType
};