/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Term } from './term';

export interface ClassSubjectResultUpdateDto { 
    term?: Term;
    sessionId?: string;
    classSubjectId?: string;
    studentId?: string;
    caScore?: number;
    examScore?: number;
    id?: string;
}