/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
import { Religion } from './religion';

export interface TeacherResponseDto { 
    teacherNo?: string;
    userId?: string;
    firstName?: string;
    lastName?: string;
    middleName?: string;
    gender?: Gender;
    religion?: Religion;
    dateOfBirth?: Date;
    originLGA?: string;
    stateOfOrigin?: string;
    nationality?: string;
    homeAddress?: string;
    residentialCity?: string;
    residentialState?: string;
    phoneNumber?: string;
    id?: string;
    email?: string;
}