import { TableHeaderInterface } from '../../../types/table';

export const tableHeader: TableHeaderInterface[] = [
  {
    key: 'logo',
    type: 'image',
    name: 'Logo',
    sortable: false,
    filterable: false,
    align: 'center',
    fallback: (row: any) => row.name?.split(' ').slice(0, 2).map((w: string) => w[0]).join('').toUpperCase() || '?',
  },
  {
    key: 'name',
    type: 'text',
    name: 'Name',
    sortable: true,
    filterable: true,
    align: 'left',
  },
  {
    key: 'shortName',
    type: 'text',
    name: 'Short Name',
    sortable: true,
    filterable: true,
    align: 'left',
  },
  {
    key: 'principalName',
    type: 'text',
    name: 'Principal',
    sortable: true,
    filterable: true,
    align: 'left',
  },
  {
    key: 'address',
    type: 'text',
    name: 'Address',
    sortable: true,
    filterable: true,
    align: 'left',
  },
  {
    key: 'domainName',
    type: 'text',
    name: 'Domain',
    sortable: true,
    filterable: true,
    align: 'left',
  },
  {
    key: 'description',
    type: 'text',
    name: 'Description',
    sortable: false,
    filterable: true,
    align: 'left',
  },
];
