name: Busco UI Deploy

on:
  push:
    branches:
      - main

env:
  WEBAPP_PACKAGE_PATH: 'dist\project-ui\browser'
  NODE_VERSION: '18.17.0'

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install
      run: npm ci --force

    - name: npm build
      run: npm run build-prod-busco

    - name: Copy web config
      run: |
        cmd /c 'copy web.config ${{ env.WEBAPP_PACKAGE_PATH }} /y'

    - name: Copy well-known folder
      run: |
        cmd xcopy .well-known dist\project-ui\browser\.well-known /E /I /Y

    - name: Deploy to SmarterASP.NET
      shell: powershell
      run: |
        $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"

        $siteName = '${{ secrets.WEBSITE_NAME_BUSCO }}'
        $computer = '${{ secrets.SERVER_COMPUTER_NAME }}'
        $user     = '${{ secrets.SERVER_USERNAME }}'
        $password = '${{ secrets.SERVER_PASSWORD_BUSCO }}'

        & $msdeploy `
          -verb:sync `
          -source:contentPath="$(pwd)\${{ env.WEBAPP_PACKAGE_PATH }}" `
          -dest:contentPath="$siteName",ComputerName="$computer",UserName="$user",Password="$password",AuthType="Basic" `
          -allowUntrusted `
          -enableRule:AppOffline `
          -enableRule:DoNotDeleteRule
